version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_registro_horario
    environment:
      POSTGRES_DB: registro_horario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
