services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: postgres_work_trace
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/indexes.sql:/docker-entrypoint-initdb.d/02-indexes.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/03-seed.sql
      - ./database/trigger_integrity_protection.sql:/docker-entrypoint-initdb.d/04-trigger_integrity_protection.sql

volumes:
  postgres-data:
